### ISSUE TITLE
error: uncaughtException: Object function Object() { [native code] } has no method 'assign' 

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-cloud#100]
Hi,

I updated the old code by git pull and did npm install, now I am getting below error.

$ node -v
v0.10.48

$ sudo node app.js 

2017-05-12T10:51:41.798Z - info: openHAB-cloud: Backend service is starting up...
2017-05-12T10:51:41.805Z - info: openHAB-cloud: Backend logging initialized...
2017-05-12T10:51:42.297Z - error: uncaughtException: Object function Object() { [native code] } has no method 'assign' date=Fri May 12 2017 10:51:42 GMT+0000 (UTC), pid=7783, uid=0, gid=0, cwd=/home/ubuntu/openhab-cloud, execPath=/usr/local/bin/node, version=v0.10.48, argv=[node, /home/ubuntu/openhab-cloud/app.js], rss=36888576, heapTotal=31139328, heapUsed=15028000, loadavg=[0.080078125, 0.0166015625, 0.00537109375], uptime=11845809.731648784, trace=[column=8, file=/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/@xmpp/xml/index.js, function=, line=10, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=15, file=/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/Connection.js, function=, line=6, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=18, file=/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/index.js, function=, line=3, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false], stack=[TypeError: Object function Object() { [native code] } has no method 'assign',     at Object.<anonymous> (/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/@xmpp/xml/index.js:10:8),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/Connection.js:6:15),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/home/ubuntu/openhab-cloud/node_modules/node-xmpp/node_modules/node-xmpp-core/index.js:3:18),     at Module._compile (module.js:456:26)]
2017-05-12T10:51:42.298Z - error:

**Comment by marziman** [comment]
Please first ask in the community before opening issues. You re on the weong node version. Update to node 7.5.

**Comment by kirantpatil** [comment]
Yes Sir, Thanks.

Now it works.
