### ISSUE TITLE
Docker compose - Cannot find module './system'

### ISSUE THREAD

**Issue by jmccoy555** [openhab/openhab-cloud#131]
Hi, I think there may be an issue with docker. I've pulled the git directory copied and updated the config.json and then run docker compose but get the following;

app-1      | 2017-10-29T15:09:43.401Z - error: uncaughtException: Cannot find module './system' date=Sun Oct 29 2017 16:09:43 GMT+0100 (CET), pid=1, uid=100, gid=65533, cwd=/opt/openhabcloud, execPath=/usr/bin/node, version=v7.10.1, argv=[/usr/bin/node, /opt/openhabcloud/app.js], rss=28151808, heapTotal=8388608, heapUsed=4948976, external=88746, loadavg=[2.5009765625, 2.25927734375, 1.84423828125], uptime=7246, trace=[column=15, file=module.js, function=Module._resolveFilename, line=470, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=418, method=_load, native=false, column=17, file=module.js, function=Module.require, line=498, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=/opt/openhabcloud/app.js, function=null, line=23, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=580, method=.js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Module._load, line=439, method=_load, native=false], stack=[Error: Cannot find module './system',     at Function.Module._resolveFilename (module.js:470:15),     at Function.Module._load (module.js:418:25),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/opt/openhabcloud/app.js:23:14),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3)]

Any ideas?

Thanks

**Comment by marziman** [comment]
Hi @jmccoy555,

did this work for you now?
If this is resolved, let me know otherwise I am going to close the issue. If not, let me know how I can assist you.

Thx & BR
Mehmet

**Comment by jmccoy555** [comment]
Hi @marziman just seen your reply, thanks. I'll give it another go in the next few days and let you know. It was a while ago now but I'm pretty sure I followed the readme. Let me check again. 

Cheers.

**Comment by jmccoy555** [comment]
Hi @marziman 

I've tried to reproduce this but I can't really remember what I was trying to do back in Oct 17, I think I was trying to run it in Ubuntu as I couldn't get the Docker way to work. Ultimately I would just like to build the docker image without using compose, is this possible? I already have redis, mongodb and nginx running. 

I have tried cloning the git, cd into the dir, cp config-production.json -> config.json then, 

 docker build -t openhab/openhab-cloud docker/node/.

The build completes but it fails to start. 

Thanks for your help.
