### ISSUE TITLE
Error running npm install: `error: use of undeclared identifier 'daylight'`

### ISSUE THREAD

**Issue by holmes** [openhab/openhab-cloud#149]
I'm trying to set up a local instance of openhab cloud so I can do some google home integration but I'm running into a slew of problems.

I'm hosting this on a FreeBSD jail which but I've got is mostly working. I've gotten to the point where I need to run `npm install` but I'm running into 2 compilation errors in the time library.

```
../src/time.cc:56:80: error: use of undeclared identifier 'daylight'
    Nan::Set(obj, Nan::New("daylight").ToLocalChecked(), Nan::New<v8::Number>( daylight ));
                                                                               ^
In file included from ../src/time.cc:5:
In file included from ../../nan/nan.h:196:
../../nan/nan_new.h:208:31: error: cannot initialize a parameter of type 'double' with an lvalue of type 'char *(*)(int, int)'
  return imp::Factory<T>::New(arg0);
```

Here's the full build. Note that I apparently have to compile bcrypt on my own (which seems to work)
```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v59-freebsd-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)
```

Full logs:

```
root@openhab_cloud:/var/www/openhab.thejholmes.com/openhab-cloud # npm install
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated mongodb@1.4.40: Please upgrade to 2.2.19 or higher
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated mongodb@2.1.8: Please upgrade to 2.2.19 or higher
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> typechecker@2.0.8 preinstall /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> bcrypt@0.8.7 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt-cache/node_modules/bcrypt
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt-cache/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt-cache/node_modules/bcrypt/build'

> bson@0.2.22 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bson/build'

> kerberos@0.0.11 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/kerberos/build'

> bufferutil@1.2.1 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bufferutil
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bufferutil/build'

> ws@0.4.31 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/socket.io-client/node_modules/ws/build'

> utf-8-validate@1.2.2 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/utf-8-validate
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/utf-8-validate/build'

> bcrypt@1.0.2 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v59-freebsd-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)
gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/bcrypt/build'

> heapdump@0.3.7 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/heapdump
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/heapdump/build'
(node:72450) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

> hiredis@0.4.1 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/hiredis
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../src/hiredis.cc:1:
In file included from ../src/reader.h:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  CXX(target) Release/obj.target/hiredis/src/reader.o
In file included from ../src/reader.cc:3:
In file included from ../src/reader.h:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/hiredis/build'

> memwatch-next@0.3.0 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/memwatch-next
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/memwatch-next/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:12:
In file included from ../src/heapdiff.hh:11:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  CXX(target) Release/obj.target/memwatch/src/init.o
In file included from ../src/init.cc:8:
In file included from ../src/heapdiff.hh:11:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
../src/init.cc:20:17: warning: 'AddGCEpilogueCallback' is deprecated [-Wdeprecated-declarations]
        v8::V8::AddGCEpilogueCallback(memwatch::after_gc);
                ^
/root/.node-gyp/9.3.0/include/node/v8.h:7927:12: note: 'AddGCEpilogueCallback' has been explicitly marked deprecated here
      void AddGCEpilogueCallback(GCCallback callback,
           ^
2 warnings generated.
  CXX(target) Release/obj.target/memwatch/src/memwatch.o
In file included from ../src/memwatch.cc:6:
In file included from ../src/memwatch.hh:9:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  CXX(target) Release/obj.target/memwatch/src/util.o
  SOLINK_MODULE(target) Release/obj.target/memwatch.node
  COPY Release/memwatch.node
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/memwatch-next/build'

> time@0.11.4 install /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/time
> node-gyp rebuild

gmake: Entering directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/time/build'
  CXX(target) Release/obj.target/time/src/time.o
In file included from ../src/time.cc:5:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/root/.node-gyp/9.3.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
../src/time.cc:56:80: error: use of undeclared identifier 'daylight'
    Nan::Set(obj, Nan::New("daylight").ToLocalChecked(), Nan::New<v8::Number>( daylight ));
                                                                               ^
In file included from ../src/time.cc:5:
In file included from ../../nan/nan.h:196:
../../nan/nan_new.h:208:31: error: cannot initialize a parameter of type 'double' with an lvalue of type 'char *(*)(int, int)'
  return imp::Factory<T>::New(arg0);
                              ^~~~
../src/time.cc:52:63: note: in instantiation of function template specialization 'Nan::New<v8::Number, char *(*)(int, int)>' requested here
    Nan::Set(obj, Nan::New("timezone").ToLocalChecked(), Nan::New<v8::Number>( timezone ));
                                                              ^
../../nan/nan_implementation_12_inl.h:146:33: note: passing argument to parameter 'value' here
Factory<v8::Number>::New(double value) {
                                ^
1 warning and 2 errors generated.
gmake: *** [time.target.mk:95: Release/obj.target/time/src/time.o] Error 1
gmake: Leaving directory '/var/www/openhab.thejholmes.com/openhab-cloud/node_modules/time/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System FreeBSD 11.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/openhab.thejholmes.com/openhab-cloud/node_modules/time
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN grunt-qunit-node@0.1.0 requires a peer of qunitjs@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! time@0.11.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the time@0.11.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-20T00_26_29_696Z-debug.log
root@openhab_cloud:/var/www/openhab.thejholmes.com/openhab-cloud #
```

**Comment by marziman** [comment]
Hi @holmes ,

do you run the right Node version, which is used by openhab-cloud? Looks like you run some node v9.3.0 ?
And I think this looks more like a local build problem intead of an openhab-cloud issue.
Can you please retry it with the corresponding node version? I never saw this error message ever before.
I will close it, and if you still think this is an issue..feel free to re-open it.
BR Mehmet
