### ISSUE TITLE
OpenHab Cloud behind reverse proxy and OAuth

### ISSUE THREAD

**Issue by marceltoepler** [openhab/openhab-cloud#186]
I try to set up OpenHab Cloud with the Google Assistant functions.

I got everything ready and working, but I cannot link the Google Assistant with my OpenHab Cloud instance.

In Google Home app i got a error message:

> The setting could not be updated. Check your connection.

Looking in the logs from OpenHab Cloud, I found the following:

    2018-04-14T08:09:42.940Z - info: openHAB-cloud: server.authorization oauth2 request for scope: google-assistant
    ForbiddenError: invalid csrf token
        at csrf (/root/openhab-cloud/node_modules/csurf/index.js:112:19)
        at /root/openhab-cloud/app.js:269:9
        at Layer.handle [as handle_request] (/root/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/root/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
        at /root/openhab-cloud/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/root/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
        at Context.next (/root/openhab-cloud/node_modules/express/lib/router/index.js:275:10)
        at Context.actions.pass (/root/openhab-cloud/node_modules/passport/lib/passport/context/http/actions.js:77:8)
        at SessionStrategy.authenticate (/root/openhab-cloud/node_modules/passport/lib/passport/strategies/session.js:67:10)
        at attempt (/root/openhab-cloud/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
        at Passport.authenticate (/root/openhab-cloud/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
        at Layer.handle [as handle_request] (/root/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/root/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
        at /root/openhab-cloud/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/root/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
        at next (/root/openhab-cloud/node_modules/express/lib/router/index.js:275:10)
        at Passport.initialize (/root/openhab-cloud/node_modules/passport/lib/passport/middleware/initialize.js:69:5)
        at Layer.handle [as handle_request] (/root/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/root/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
        at /root/openhab-cloud/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/root/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
        at next (/root/openhab-cloud/node_modules/express/lib/router/index.js:275:10)

I am running OpenHabCloud behind a apache2 reverse proxy, if this matters. The configuration file looks like that:

    ProxyPreserveHost On
    ProxyRequests off
    ProxyPass / http://192.168.1.119:3000/
    ProxyPassReverse / http://192.168.1.119:3000/

Maybe that is the problem?

Thank you!

**Comment by FlorianSW** [comment]
Hi!

This looks, to me, like a support request rather than a bug, isn't it? Maybe you want to ask this question in the [openHAB community](https://community.openhab.org/). Issues at github should be used for bugs in the software or for feature requests :)

Best,
Florian

**Comment by marceltoepler** [comment]
Hey,

I think you're right and this is not a bug. I already asked in the openHAB community, but I don't got an answer that helps me there so I thought that somebody can help me here. 

Regards 
Marcel

**Comment by marziman** [comment]
Hi,

this can have different reasons and looks like more a Google Assistant related topic.
It is difficult to understand with little information.
The best way is to ask at the forum, where I can assist you maybe with this.

Can you please linke me there and provide a detailed explanation of your question?

BR Mehmet

**Comment by kirantpatil** [comment]
I am also having same issue, where to find the solution ?

**Comment by kirantpatil** [comment]
Below code is causing the issue.

```
app.use(flash());
app.use(passport.initialize());
app.use(passport.session());
app.use(function (req, res, next) {
    var csrf = csurf();
    // Check if url needs csrf
    if (!req.path.match('/rest*') && !req.path.match('/oauth2/token') && !req.path.match('/ifttt/*'))
        csrf(req, res, next);    //Line 269 is where the error showing on console
    else
        next();
});

```
