### ISSUE TITLE
error: uncaughtException: Cannot find module './config.json'

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-cloud#22]
Hi,

I followed the Quickstart guide to install openhab-cloud on ubuntu 16.04. But I am getting below error while starting the app.

#### $ node --version
v0.10.48

#### $ sudo node app.js

2017-01-04T12:41:35.479Z - info: openHAB-cloud: Backend service is starting up...
2017-01-04T12:41:35.484Z - info: openHAB-cloud: Backend logging initialized...
2017-01-04T12:41:35.489Z - error: uncaughtException: Cannot find module './config.json' date=Wed Jan 04 2017 12:41:35 GMT+0000 (UTC), pid=24452, uid=0, gid=0, cwd=/home/ubuntu/openhab-cloud, execPath=/usr/local/bin/node, version=v0.10.48, argv=[node, /home/ubuntu/openhab-cloud/app.js], rss=17514496, heapTotal=9293056, heapUsed=3399584, loadavg=[0.02001953125, 0.13427734375, 0.076171875], uptime=793202.923608907, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=338, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=280, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=14, file=/home/ubuntu/openhab-cloud/app.js, function=, line=35, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=497, method=Module.runMain, native=false], stack=[Error: Cannot find module './config.json',     at Function.Module._resolveFilename (module.js:338:15),     at Function.Module._load (module.js:280:25),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/home/ubuntu/openhab-cloud/app.js:35:14),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Function.Module.runMain (module.js:497:10)]
2017-01-04T12:41:35.490Z - error:  code=MODULE_NOT_FOUND

**Comment by kirantpatil** [comment]
found answer in forum https://community.openhab.org/t/openhab-cloud-installation/18798/2

**Comment by Stefan300381** [comment]
Hi,

in deed config.json does not exist after cloning from git. This should be mentioned in the Readme
