### ISSUE TITLE
[development mode] error: uncaughtException: Cannot read property 'password' 

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-cloud#23]
I copied config-development.json to config.json and tried to run the app and it results in below error.

$ sudo node app.js 
2017-01-04T13:21:11.358Z - info: openHAB-cloud: Backend service is starting up...
2017-01-04T13:21:11.364Z - info: openHAB-cloud: Backend logging initialized...
2017-01-04T13:21:12.647Z - info: openHAB-cloud: Mailer will emulate sending in development environment
2017-01-04T13:21:12.944Z - error: uncaughtException: Cannot read property 'password' of undefined date=Wed Jan 04 2017 13:21:12 GMT+0000 (UTC), pid=25076, uid=0, gid=0, cwd=/home/ubuntu/openhab-cloud, execPath=/usr/local/bin/node, version=v0.10.48, argv=[node, /home/ubuntu/openhab-cloud/app.js], rss=81817600, heapTotal=69575168, heapUsed=41610520, loadavg=[0.06689453125, 0.015625, 0.00439453125], uptime=795580.377863331, trace=[column=42, file=/home/ubuntu/openhab-cloud/gcmsender.js, function=, line=7, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=17, file=/home/ubuntu/openhab-cloud/routes/devices.js, function=, line=10, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=24, file=/home/ubuntu/openhab-cloud/app.js, function=, line=55, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false], stack=[TypeError: Cannot read property 'password' of undefined,     at Object.<anonymous> (/home/ubuntu/openhab-cloud/gcmsender.js:7:42),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/home/ubuntu/openhab-cloud/routes/devices.js:10:17),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (/home/ubuntu/openhab-cloud/app.js:55:24),     at Module._compile (module.js:456:26)]
2017-01-04T13:21:12.945Z - error:

**Comment by marziman** [comment]
Please have little patience, this will be fixed with https://github.com/openhab/openhab-cloud/pull/21

**Comment by kirantpatil** [comment]
There was no issue pertaining to this error, so I raised one.

Thank you.

**Comment by marziman** [comment]
This should be fixed with [21](https://github.com/openhab/openhab-cloud/pull/21)
