### ISSUE TITLE
Winston not found?

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-cloud#266]
Hi Team,
Im getting this error after the installation, can someone please provide some assitance/guidance?

0| Cloud  | { Error: Cannot find module 'winston'
0| Cloud  |     at Function.Module._resolveFilename (module.js:547:15)
0| Cloud  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:27)
0| Cloud  |     at require (internal/module.js:11:18)
0| Cloud  |     at Object.<anonymous> (/var/www/Cloud/logger.js:7:15)
0| Cloud  |     at Module._compile (module.js:652:30)
0| Cloud  |     at Object.Module._extensions..js (module.js:663:10)
0| Cloud  |     at Module.load (module.js:565:32)
0| Cloud  |     at tryModuleLoad (module.js:505:12)
0| Cloud  |     at Function.Module._load (module.js:497:3)
0| Cloud  |     at Module.require (module.js:596:17) code: 'MODULE_NOT_FOUND' }

thank you

**Comment by dastrix80** [comment]
Be great if someone could response to this. ive tried about 10 different things

using node version 8.10.0, but node 7 does the same thing

Installing the winston module just makes it worse!
