### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-cloud#273]
Hi Guys,

There are issues in the instructions. I installed node, using the v7.10.1 as per your recommendations and followed things line by line.

The app doesnt start. Ive tried loads of node versions, every single one has issues :/

 node
> app.js
ReferenceError: app is not defined
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:241:10)
    at REPLServer.Interface._line (readline.js:590:8)
>

This occurs for many people. Can someone please update the instructions so they reflect a correct and working install.

Thanks

**Comment by andyjkr** [comment]
Seriously. I wonder if whoever wrote ANY of these instructions for any aspect of openhab understands the concept of complete step by step instructions, or if they perhaps expect a mind reading script to be running in our brains.

**Comment by dastrix80** [comment]
Yeah, the documentation leaves alot to be desired im afraid :(
