### ISSUE TITLE
Private instance of Cloud , been working for over 12 months njow Socket.IO errors

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-cloud#308]
Hi @digitaldan I know this is discussed ALOT on the forums for myopenhab.org yet theres no real clue as to what the fix has been

I'm now seeing these errors, my instance is online, I can login to the private cloud just fine and everything works EXCEPT when a sendBroadcastNotification is sent to Firebase, the Cloud connect restarts and NGINX indicates socket.IO errors. Can you explain what the fix has been? Its odd this has suddenly started happening.

08:29:31.807 [ERROR] [.io.openhabcloud.internal.CloudClient] - Socket.IO error: {}
io.socket.engineio.client.EngineIOException: websocket error
        at io.socket.engineio.client.Transport.onError(Transport.java:71) [251:org.openhab.io.openhabcloud:2.4.0]
        at io.socket.engineio.client.transports.WebSocket.access$500(WebSocket.java:28) [251:org.openhab.io.openhabcloud:2.4.0]
        at io.socket.engineio.client.transports.WebSocket$2$5.run(WebSocket.java:150) [251:org.openhab.io.openhabcloud:2.4.0]
        at io.socket.thread.EventThread$2.run(EventThread.java:80) [251:org.openhab.io.openhabcloud:2.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:59) ~[?:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:72) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:115) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:104) ~[?:?]
        at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97) ~[?:?]
        at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152) ~[?:?]
        at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41) ~[?:?]
        at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97) ~[?:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126) ~[?:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[?:?]
        ... 3 more

**Comment by sennl** [comment]
Same here. @dastrix80 did you find a solution?

**Comment by learningcicd** [comment]
Note the solution here.
You need to check the openhab-cloud logs, when send the notification it will show error. Fixed the error and it should be working fine.
In my case, APN setting have problem (cert expired), it will also need to android not receiving the notification.
