### ISSUE TITLE
service not starting - apn related?

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-cloud#342]
When moving from S2300 to S2306 I had some issues with my cloud connector (connecting locally was just fine) and the basicui.  I attempted to update to see if it was due to my cloud connector being old.  New install is now not coming up.  I'm on Ubuntu 16 with Node 14.  This is all I get:

/opt/openhab-cloud# node app.js
{"errno":-2,"syscall":"open","code":"ENOENT","path":"certs/aps/AuthKey.p8"}
(node:11903) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
node_redis: Warning: Redis server does not require a password, but a password was supplied.

I'm concerned that the recent APN changes could be causing an issue because I don't use apple products.  Logs show:

2021-04-03 20:13:49:4949 error: uncaughtException: ENOENT: no such file or directory, open 'certs/aps/AuthKey.p8'
Error: ENOENT: no such file or directory, open 'certs/aps/AuthKey.p8'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (/opt/openhab-cloud/notificationsender/aps-helper.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/openhab-cloud/app.js:90:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by morph166955** [comment]
Others seem to be having this issue as well... 

https://community.openhab.org/t/setup-your-own-openhab-cloud-myopenhab-server-instance/24716
