### ISSUE TITLE
Server is not running, Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by vancako** [openhab/openhab-cloud#358]
Hi,
unfortunately I can't successfully lunch the cloud server. There is my error log
I am using node v14.18.0, npm 7.24.1.

2021-10-03 18:11:23:2323 info: openHAB-cloud: Backend service is starting up...
2021-10-03 18:11:23:2323 info: openHAB-cloud: Backend logging initialized...
2021-10-03 18:11:23:2323 info: openHAB-cloud: Initializing XMPP connection to GCM
2021-10-03 18:11:24:2424 info: openHAB-cloud: Connecting to Redis at 127.0.0.1:6379
2021-10-03 18:11:25:2525 info: openHAB-cloud: Mailer will emulate sending in development environment
2021-10-03 18:11:25:2525 error: uncaughtException: Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/var/www/my_server.bla/openhab-cloud/node_modules/express-form/lib/field.js:2:40)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/my_server.bla/openhab-cloud/node_modules/express-form/lib/form.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)

**Comment by saxika1291** [comment]
Hi, I get the same error with node v16.13.0 and npm 8.1.2.
