### ISSUE TITLE
[Docker-Compose] pull access denied for openhab/openhabcloud-app

### ISSUE THREAD

**Issue by EnziinSystem** [openhab/openhab-cloud#378]
When I pull images:

`docker-compose pull`

The error:

```
[+] Running 0/4
 ⠿ app Error                                                                                                                                                                             4.1s
 ⠋ mongodb Pulling                                                                                                                                                                       4.1s
 ⠋ redis Pulling                                                                                                                                                                         4.1s
   ⠋ 3b5e91f25ce6 Pulling fs layer                                                                                                                                                       0.0s
   ⠋ e32cf6583f90 Pulling fs layer                                                                                                                                                       0.0s
   ⠋ 7edef941d8e9 Pulling fs layer                                                                                                                                                       0.0s
   ⠋ 54a1e6d39f13 Waiting                                                                                                                                                                0.0s
   ⠋ babe893252c5 Waiting                                                                                                                                                                0.0s
   ⠋ 2036778babf7 Waiting                                                                                                                                                                0.0s
   ⠋ bcc0f4915147 Waiting                                                                                                                                                                0.0s
   ⠋ b05c7c7e1449 Waiting                                                                                                                                                                0.0s
   ⠋ 554b5c456859 Waiting                                                                                                                                                                0.0s
   ⠋ 1ec7b8f81f15 Waiting                                                                                                                                                                0.0s
   ⠋ 386460bb1899 Waiting                                                                                                                                                                0.0s
   ⠋ f9e96979161d Waiting                                                                                                                                                                0.0s
 ⠿ traefik Error                                                                                                                                                                         4.1s
WARNING: Some service image(s) must be built from source by running:
    docker compose build app
Error response from daemon: pull access denied for openhab/openhabcloud-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by thedolt** [comment]
@jasonxh I have the same issue.

**Comment by jasonxh** [comment]
Looks like the official docker repo has been renamed to `openhab/openhab-cloud` (original name was `openhab/openhabcloud-app`) sometime ago, and `docker-compose.yml` hasn't been updated yet. I can cook up a short PR. In the meantime, you can make the change locally on [this line](https://github.com/openhab/openhab-cloud/blob/main/deployment/docker-compose/docker-compose.yml#L5) to unblock yourself.

**Comment by thedolt** [comment]
@jasonxh Just curious, but do you know if there are any plans for an ARM64 release of that image?  I'm currently using your image jasonxh/openhabcloud-app because it works with my ARM architecture.  Also, have you considered creating an ARMv7 or ARM64 variant of the docker-compose file where all the images are ARM compatible?  I'm only asking because I just discovered that bitnami/redis doesn't have an arm64 image.  I don't know anything about redis.  Do you know if I could use Docker's official open source redis image in its place?

Cheers!

**Comment by thedolt** [comment]
Correction, I tried using jasonxh/openhabcloud-app.  It doesn't appear to be working.  I'm trying to run it as a system service and get the following in my logs:

Aug 11 23:06:34 raspberrypi docker[986]: Error: ENOENT: no such file or directory, open 'null/configuration.yaml'
Aug 11 23:06:39 raspberrypi docker[986]:     at Object.openSync (node:fs:585:3)
Aug 11 23:06:39 raspberrypi docker[986]:     at Object.readFileSync (node:fs:453:35)
Aug 11 23:06:39 raspberrypi docker[986]:     at Object.read (/app/lib/util/yaml.ts:7:29)
Aug 11 23:06:39 raspberrypi docker[986]:     at read (/app/lib/util/settings.ts:311:20)
Aug 11 23:06:39 raspberrypi docker[986]:     at getInternalSettings (/app/lib/util/settings.ts:418:21)
Aug 11 23:06:39 raspberrypi docker[986]:     at Object.reRead (/app/lib/util/settings.ts:696:5)
Aug 11 23:06:39 raspberrypi docker[986]:     at start (/app/index.js:93:14)

So at this point, I have no viable container solution for this.  This is super disappointing because I was hoping to containerize this with all over my other home automation applications.

**Comment by jasonxh** [comment]
@thedolt I'm not an official maintainer so I don't know if there's any plan to release ARM images. However, I'm also running the entire setup on ARM64 (using my custom built image). For redis in particular, I've been using the official `redis:6.2` image, but the password configuration mechanism is different. The simple solution is to remove the password config by deleting [this line](https://github.com/openhab/openhab-cloud/blob/main/deployment/docker-compose/config.json.template#L35). It's fine because the redis port is never exposed outside of your docker network anyway.

The stack trace you shared doesn't look familiar at all. I suspect it didn't come from the `openhab-cloud` app. Might be some issue with your docker setup, but hard to say just based on the above.
