### ISSUE TITLE
Error at logout

### ISSUE THREAD

**Issue by Wonko52** [openhab/openhab-cloud#407]
When logging out at the web ui, the following error message appears:

```
Error: req#logout requires a callback function
    at IncomingMessage.req.logout.req.logOut (/opt/openhabcloud/node_modules/passport/lib/http/request.js:65:44)
    at /opt/openhabcloud/routes/index.js:77:13
    at Layer.handle [as handle_request] (/opt/openhabcloud/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/openhabcloud/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/openhabcloud/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/openhabcloud/node_modules/express/lib/router/layer.js:95:5)
    at /opt/openhabcloud/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/openhabcloud/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/openhabcloud/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/opt/openhabcloud/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:400:28)
    at SendStream.error (/opt/openhabcloud/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/opt/openhabcloud/node_modules/send/index.js:421:12)
    at next (/opt/openhabcloud/node_modules/send/index.js:735:16)
    at onstat (/opt/openhabcloud/node_modules/send/index.js:724:14)
    at FSReqCallback.oncomplete (fs.js:192:21)
```

I use the Docker image openhab/openhab-cloud:latest

Connections with the app work fine.

**Comment by KailashShewtahul** [comment]
I have the same issue. Have you found a solution?
