### ISSUE TITLE
v7.5 issue with emails

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-cloud#46]
Sending emails does not work with 7.5, below is a error output 

```- error: uncaughtException: Path must be a string. Received undefined date=Thu Feb 16 2017 03:27:13 GMT+0000 (UTC), pid=19667, uid=1000, gid=1000, cwd=/home/openhabcloud/openhabcloud, execPath=/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, version=v7.5.0, argv=[/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, /home/openhabcloud/openhabcloud/app.js], rss=435642368, heapTotal=378830848, heapUsed=169432064, external=32748256, loadavg=[0.43701171875, 0.71728515625, 0.70361328125], uptime=301618, trace=[column=11, file=path.js, function=assertPath, line=7, method=null, native=false, column=5, file=path.js, function=Object.extname, line=1431, method=extname, native=false, column=26, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/templateManager.js, function=Object.render, line=35, method=render, native=false, column=17, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=null, line=246, method=null, native=false, column=13, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=null, line=122, method=null, native=false, column=13, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=_each, line=46, method=null, native=false, column=9, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=async.each, line=121, method=each, native=false, column=13, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=_asyncMap, line=245, method=null, native=false, column=23, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=Object.map, line=216, method=map, native=false, column=11, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/main.js, function=Object.EmailTemplate.render, line=71, method=EmailTemplate.render, native=false, colu
Feb 16 03:27:13 ubuntu openhabcloud[19667]: mn=23, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/main.js, function=batchCheck, line=158, method=null, native=false, column=17, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/main.js, function=null, line=229, method=null, native=false, column=17, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=null, line=251, method=null, native=false, column=19, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=done, line=132, method=null, native=false, column=16, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=null, line=32, method=null, native=false, column=21, file=/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js, function=null, line=248, method=null, native=false], stack=[TypeError: Path must be a string. Received undefined,     at assertPath (path.js:7:11),     at Object.extname (path.js:1431:5),     at Object.render (/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/templateManager.js:35:26),     at /home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:246:17,     at /home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:122:13,     at _each (/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:46:13),     at async.each (/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:121:9),     at _asyncMap (/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:245:13),     at Object.map (/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:216:23),     at Object.EmailTemplate.render (/home/openhabcloud/openhabcloud/node_modules/email-templates/lib/main.js:71:11),     at batchCheck (/home/openhabcloud/openhabcloud/node_
Feb 16 03:27:13 ubuntu openhabcloud[19667]: modules/email-templates/lib/main.js:158:23),     at /home/openhabcloud/openhabcloud/node_modules/email-templates/lib/main.js:229:17,     at /home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:251:17,     at done (/home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:132:19),     at /home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:32:16,     at /home/openhabcloud/openhabcloud/node_modules/email-templates/node_modules/async/lib/async.js:248:21]
```

**Comment by digitaldan** [comment]
A little digging shows this is being thrown by the built in path module in node.  It looks like a path at email-templates/lib/templateManager.js line 35 is undefined.  My first thought is to upgrade email-template to the latest version and see if that fixes it.

**Comment by marziman** [comment]
Did you try this out? Should I check this?

**Comment by digitaldan** [comment]
That would be great, I will work on the GCM issue since I think I will need to actually test notifications to make sure something is not broken there.

**Comment by marziman** [comment]
Should be fixed with https://github.com/openhab/openhab-cloud/pull/49

**Comment by marziman** [comment]
Fixed with https://github.com/openhab/openhab-cloud/pull/49
