### ISSUE TITLE
v7.5 issue with error logger

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-cloud#47]
an error message is being thrown about logger.err not being a function, not sure what this is breaking (GCM functionality?) , but needs to be addressed. 

```error: uncaughtException: logger.err is not a function date=Thu Feb 16 2017 03:25:41 GMT+0000 (UTC), pid=19667, uid=1000, gid=1000, cwd=/home/openhabcloud/openhabcloud, execPath=/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, version=v7.5.0, argv=[/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, /home/openhabcloud/openhabcloud/app.js], rss=431296512, heapTotal=375685120, heapUsed=165458040, external=31273907, loadavg=[0.8017578125, 0.822265625, 0.72998046875], uptime=301526, trace=[column=48, file=/home/openhabcloud/openhabcloud/gcm-xmpp.js, function=null, line=95, method=null, native=false, column=24, file=/home/openhabcloud/openhabcloud/node_modules/node-gcm/lib/sender.js, function=null, line=35, method=null, native=false, column=24, file=/home/openhabcloud/openhabcloud/node_modules/node-gcm/lib/sender.js, function=Request._callback, line=163, method=_callback, native=false, column=22, file=/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js, function=Request.self.callback, line=186, method=self.callback, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Request.emit, line=192, method=emit, native=false, column=10, file=/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js, function=, line=1081, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Request.emit, line=189, method=emit, native=false, column=12, file=/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js, function=, line=1001, method=null, native=false, column=19, file=events.js, function=Object.onceWrapper, line=291, method=onceWrapper, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=186, method=emit, native=false, column=12, file=_strea
Feb 16 03:25:41 ubuntu openhabcloud[19667]: m_readable.js, function=endReadableNT, line=974, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[TypeError: logger.err is not a function,     at /home/openhabcloud/openhabcloud/gcm-xmpp.js:95:48,     at /home/openhabcloud/openhabcloud/node_modules/node-gcm/lib/sender.js:35:24,     at Request._callback (/home/openhabcloud/openhabcloud/node_modules/node-gcm/lib/sender.js:163:24),     at Request.self.callback (/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js:186:22),     at emitTwo (events.js:106:13),     at Request.emit (events.js:192:7),     at Request.<anonymous> (/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js:1081:10),     at emitOne (events.js:96:13),     at Request.emit (events.js:189:7),     at IncomingMessage.<anonymous> (/home/openhabcloud/openhabcloud/node_modules/node-gcm/node_modules/request/request.js:1001:12),     at Object.onceWrapper (events.js:291:19),     at emitNone (events.js:91:20),     at IncomingMessage.emit (events.js:186:7),     at endReadableNT (_stream_readable.js:974:12),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
Feb 16 03:25:41 ubuntu openhabcloud[19667]: 2017-02-16T03:25:41.904Z - error:
```

**Comment by digitaldan** [comment]
So this should be logger.error  not logger.err so thats any easy fix, but the question is why are we suddenly hitting this error statement now, where before we were not?

**Comment by digitaldan** [comment]
I have a fix for this and will try it out soon on my own box, will require a GCM account to test

**Comment by marziman** [comment]
ok thanks @digitaldan . Looks like a easy thing. Did you change on purpose the param to err instead of result. Why did we log the result before?

**Comment by digitaldan** [comment]
Well, like I said it looks like we never threw an error before so this code was not being hit , but why would u print the result when it's the error u care about ? The result would most likely be null anyways.  So long answer to yes i did mean to change that

**Comment by marziman** [comment]
Makes sense of course. I also gonna test now.
