### ISSUE TITLE
openHAB considered offline for missing error handler in socket.io

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-cloud#95]
After some time, the following error messages occured in the openHAB-cloud log:
```
2017-05-03T07:11:17.108Z - debug: openHAB-cloud: Checking orphaned rest requests (0)
^[[0mGET /basicui/app?w=0102&sitemap=erster_versuch ^[[33m401 ^[[0m6.521 ms - -^[[0m
^[[0mGET /basicui/app?w=0102&sitemap=erster_versuch ^[[32m200 ^[[0m124.317 ms - 7921^[[0m
Missing error handler on `socket`.
TypeError: Cannot read property 'openhab' of undefined
    at Socket.<anonymous> (/opt/openhab_cloud/app.js:1079:64)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/opt/openhab_cloud/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/opt/openhab_cloud/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/opt/openhab_cloud/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/opt/openhab_cloud/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/openhab_cloud/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/opt/openhab_cloud/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/opt/openhab_cloud/node_modules/engine.io/lib/socket.js:99:14)
    at emitOne (events.js:82:20)
    at WebSocket.emit (events.js:169:7)
    at WebSocket.Transport.onPacket (/opt/openhab_cloud/node_modules/engine.io/lib/transport.js:91:8)
    at WebSocket.Transport.onData (/opt/openhab_cloud/node_modules/engine.io/lib/transport.js:102:8)
    at WebSocket.onData (/opt/openhab_cloud/node_modules/engine.io/lib/transports/websocket.js:75:30)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/opt/openhab_cloud/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:816:10)
    at /opt/openhab_cloud/node_modules/engine.io/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/opt/openhab_cloud/node_modules/engine.io/node_modules/ws/lib/Receiver.js:364:5)
2017-05-03T07:11:43.039Z - info: openHAB-cloud: Disconnected e08ef154-e1af-493f-9a16-d555039eff47
^[[0mGET /icon/temperature?state=17.2&format=svg ^[[33m401 ^[[0m17.802 ms - -^[[0m
^[[0mGET /icon/slider?state=NULL&format=svg ^[[33m401 ^[[0m17.045 ms - -^[[0m
^[[0mGET /icon/switch?state=NULL&format=svg ^[[33m401 ^[[0m15.335 ms - -^[[0m
^[[0mGET /icon/number?state=NULL&format=svg ^[[33m401 ^[[0m14.168 ms - -^[[0m
^[[0mGET /chart?items=FL_HT_GT_Temp&period=h&t=1493795503027 ^[[33m401 ^[[0m13.161 ms - -^[[0m
^[[0mGET /chart?items=FL_HT_GT_Temp&period=m&t=1493795503028 ^[[33m401 ^[[0m12.566 ms - -^[[0m
^[[0mGET /chart?items=FL_HT_GT_Temp&period=W&t=1493795503028 ^[[33m401 ^[[0m11.919 ms - -^[[0m
2017-05-03T07:12:17.110Z - debug: openHAB-cloud: Checking for offline openHABs (1)
2017-05-03T07:12:17.110Z - debug: openHAB-cloud: Checking orphaned rest requests (14)
```
After that, the openHAB instance was considered as offline and won't come back online, until the app is restarted. I'm not sure, where the exact error comes from (so, why the openhab uuid does not match with the uuid of the request), however, the app shouldn't simply throw an unhandled error and stops working for this openHAB instance.

**Comment by marziman** [comment]
@FlorianSW ,
I can't reproduce this. Can you please attach how you tested this.
It seems to be not a general problem and I am not sure if we just should remove the "null" -checks.
This seems to me a little like a problem with your uuid and propably your setup.
Can you provide more infos, cause I tried the same and after a while I never had this error. Not locally and haven't seen it on my test instance.

**Comment by FlorianSW** [comment]
So, my usual test case for that is the following: A local openhab-cloud instance, as well as a local openHAB installation. Linking both of course. Then accessing the web frontend (/start/index) and clicking on PaperUI (in my setup it will take some seconds before the PaperUI is fully loaded). During the load process (e.g. directly after clicking PaperUI) Ctrl + C the openhab-cloud process (the browser should immediately stop loading the Paper UI). Now, start the openhab-cloud instance again (node app.js). After the initialization it will give you the pasted stack trace and disconnects the openHAB, as it can not handle the incoming requests from openHAB (they we're made in an older process of openhab-cloud, the requestId does therefore not exist in this process.
